"""registro historico, bitacora, roles ampliados, editar persona

Revision ID: 60ec932bd6ef
Revises: 91612f3cd3b8
Create Date: 2026-08-10 07:28:23.991300
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60ec932bd6ef'
down_revision: Union[str, None] = '91612f3cd3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_creado_en'), 'bitacora', ['creado_en'], unique=False)
    op.create_index(op.f('ix_bitacora_registro_id'), 'bitacora', ['registro_id'], unique=False)
    op.create_index(op.f('ix_bitacora_tabla'), 'bitacora', ['tabla'], unique=False)
    op.add_column(
        'personas',
        sa.Column('registro_historico', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # El tipo de la columna 'rol' queda como texto libre a nivel de base de
    # datos a propósito: SQLAlchemy ya valida los valores del lado de Python
    # (RolUsuario), y convertir a un Enum nativo en SQLite requiere recrear
    # la tabla completa (batch mode) — no aporta nada que no tengamos ya.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'registro_historico')
    op.drop_index(op.f('ix_bitacora_tabla'), table_name='bitacora')
    op.drop_index(op.f('ix_bitacora_registro_id'), table_name='bitacora')
    op.drop_index(op.f('ix_bitacora_creado_en'), table_name='bitacora')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
