"""esquema inicial

Revision ID: 87479cec31cd
Revises: 
Create Date: 2026-08-05 23:15:34.743060
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87479cec31cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('areas_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('catalogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'valor', name='uq_catalogo_tipo_valor')
    )
    op.create_index(op.f('ix_catalogos_tipo'), 'catalogos', ['tipo'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_unico', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('edad_manual', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=True),
    sa.Column('encargado_lider', sa.String(length=120), nullable=True),
    sa.Column('bautizado', sa.Boolean(), nullable=False),
    sa.Column('fecha_bautismo', sa.Date(), nullable=True),
    sa.Column('estudio_biblico', sa.String(length=60), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=120), nullable=True),
    sa.Column('telefono_emergencia', sa.String(length=30), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=10), nullable=True),
    sa.Column('eps', sa.String(length=120), nullable=True),
    sa.Column('talla', sa.String(length=10), nullable=True),
    sa.Column('como_llego', sa.String(length=120), nullable=True),
    sa.Column('fuente_datos', sa.String(length=60), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('servidor', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_inicio_servicio', sa.Date(), nullable=True),
    sa.Column('semaforo_espiritual', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id_unico'), 'personas', ['id_unico'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'LIDER', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_id', 'fecha', name='uq_evento_actividad_fecha')
    )
    op.create_index(op.f('ix_eventos_fecha'), 'eventos', ['fecha'], unique=False)
    op.create_table('persona_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('area_servicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_servicio_id'], ['areas_servicio.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'area_servicio_id', name='uq_persona_area')
    )
    op.create_table('seguimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('requiere_atencion', sa.Boolean(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguimientos_persona_id'), 'seguimientos', ['persona_id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'evento_id', name='uq_asistencia_persona_evento')
    )
    op.create_index(op.f('ix_asistencias_evento_id'), 'asistencias', ['evento_id'], unique=False)
    op.create_index(op.f('ix_asistencias_persona_id'), 'asistencias', ['persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencias_persona_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_evento_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_seguimientos_persona_id'), table_name='seguimientos')
    op.drop_table('seguimientos')
    op.drop_table('persona_area')
    op.drop_index(op.f('ix_eventos_fecha'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_personas_id_unico'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_catalogos_tipo'), table_name='catalogos')
    op.drop_table('catalogos')
    op.drop_table('areas_servicio')
    op.drop_table('actividades')
    # ### end Alembic commands ###
