"""agregar correo electronico a persona

Revision ID: 91612f3cd3b8
Revises: 87479cec31cd
Create Date: 2026-08-09 04:47:36.846772
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91612f3cd3b8'
down_revision: Union[str, None] = '87479cec31cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('correo_electronico', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'correo_electronico')
    # ### end Alembic commands ###
